services:
  petfood-db:
    image: postgres:16-alpine
    container_name: petfood-db
    environment:
      POSTGRES_USER: loki_user
      POSTGRES_PASSWORD: loki_password
      POSTGRES_DB: petfood_aggregator
    ports:
      - "5433:5432"
    volumes:
      - petfood_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U loki_user -d petfood_aggregator"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  petfood_pgdata:
